var tela = {};
var scale = 1;
class screenChronvs {
  constructor() {
    this.tela = {};
    this.scale = 1; 
  }
  connect() {
    D4.reset()
    var spi = new SPI();
    spi.setup({mosi:D19 /* sda */, sck:D18 /* scl */});
    this.tela = require("https://gabrielchristino.github.io/chronvs/ST7789.js").connect(spi, D16 /* DC */, D5 /* CE */, D23 /* RST */, function() {});
    this.tela.clear();
    return this.tela;
  }
  setFontA() {
    this.tela.setFontCustom( E.toString(require('heatshrink').decompress(atob('AC0//FACBsP4AIGvwUKgICBwQEBgkggV/wF/iEAhEggEQGoMgwEAoMIgGf8EfwkAgQHBggWCF5XgiAsBiEQkAABoFD///8GAwMBgMCAAMEgkCCwMGsEAgYlGvhSCHAICBhEImArBwEwo0Aj5EBgB+BgQEBjHwgFGiEDCgJpBIIRqBoBqB9xZIGIMgg5ZBiIXBoOAwGDK4MFK4MRgkD4OIDIOgAQInBhgCBgACCAAsHFgIALj//gPAgPEA4LxFYgMCmBoBj8HOAIlJgg6BgwFBhgCB/4CBDgMAyA8KFwI3DD4MBAgM/QYQFBdwSuCCwQAIgQgBHoQAHDgozHABIREAAZ4BNAQEBhwEBJ4IEEAAcPCANgsEDPgJgBkBABfgItBFwLmBcoJbBAQMICwUBwI7B/hFIK4UCcoX//BfMFoUGCwMUIINIhEBiEQghEBiBEBoGAoYVBvAsCXAScFoBbIFgMCFgME5EIhYsBjAqBkEbJZRiBg4EBiQCBohqBdwMEGgMQGgaGBCwMfOQJMFCwIAGgkD/EIEIMIhBtBIYUgwFAoIlBwJbBgUELgMYgEDagIAEgI1Bhk8aoOGgGCCwIsBFpdAwIdBCwMA+AnFhygDE4LlDUAMGXAMwgUDwEEjhrBIwMWCYMwTpFwgHxhC6BIoJDBS4IABcgZyEgUBhSMBmkQgOHOo0fAQNBCwYABOQMEOQIuHkByBkTABnhyGToZxBaYJxBAAkQgQfBgwZIgFgAQJMBCQLkBfIMRBQMhAQNCFoIrBJ4IhJAAQWEgGEDIMIDIK+Bgi+BhAwBiAwBCwQAKPoITBDIIWFogCBpACByBbDgIQBAA5UCfg79BW4MA4S3BCYJSBJ4UHEhMAga3BjEYHAMMgcAhgwBKgN+hEhOYOEgURW4MikEEolAhGIwERVAMikRiBoSNBocMgGf/xKBEwOAIoOALQPhNoMcd4w7BAQPgKwIEBmQMBW4MMDwNgDwPAM4NgW4kNCwMGM4QnCOwR5Ig///BtBAAMgAANAAAOAwGBUAKeBgUEAAMIAAIVBhFQkEPmAqBjwrGh7ZC4BABUgICBK4OAKgIuBZwTNDWIRrBFwLkBCwUgQwQAJh//+AWCQQJbBFrEwJwMwmEAj6RIAAd//6JOUBBEBDoJDBABU///ALihzCQhC3kEAIAQLYQYBgBxFFYIsBAQIoBFgICBLIQWGgf//g1QgP//wNKFYZyMjEP//gGaEH//4MgZhCLwRbBgQCBhACBkACBG4IVB4AVB4AVBRIItNRSChJAA3//40DsACBmAVEjACBhgCBgwkECgLtCA44YCv//IgL8SL4Q7FHwoCCGYQCCI4RsCgj8OgLWBjAiBsEYgOAhCNBiAmBiA1BkBBBoD8KCwQ3BkACBwEGQwMD+A7Lh//+AaDGgNAGgOAkAtBoAqBwEEAwJuDAYMIIoMPT48PAQPA4C0B4CCB4ApCLZQ9BhgpBigTBlACBxBABiBlBkEwmFAj+BMhblCLZaNFOQS0BoFMgFBBYN8agRmIwEhAQOBLYJaBgRaBAAKFBhDOBKgMgiBABmYdBGAIABHoJzBToQCBN4JEBAQKJBgH//5UBCxgAKgf/8AmEAQosCZ4IsIFIVgEAOAn/4FQoXCgLtCF4UwNIjpBgEGCogICE4QTDD4QMEFoYqFnACBhxlCBgXAEQY5BBQQTBAgQ9GDAQuCEooSCEgIEEBgREEZwkMAQMwHQOAgIuBgJhCDgJkDAQMgBAOA4ASBoCkBWgVAAYYzETQS2CTooFCEgLKCA478CAATmBFoJCBwENXAMiCYOEgkGhEIiAABoEgkIWBphRB0EBDQMCCwL8CABP///5AgMSHAbKHa5gMCLAWQSwM///+GxYADSYMHSQaxDdwgvDRQKqDAApSCBYQUBRYKfDOoRJCXwQWHJZwCGC5wAISQMQxEAoRBBwkQgMIkECaQMEkGAhFCKIOMgEP/jONwEDzgWBNgMQFQNAAQOAFoJvBPgItBBIMEAwMMU4MHaAQAEjwCBwKWBDoMIAQMQDIMgEAItHAQKCJgbOBiFgDIITCIgwtIkDIBkFAn//Jo4qCBQMJCYMiAQKgLoItBwUAiJYBNgQAHHQJyBgEB//+DwIHBdwMQNYs8CIMGiCgBKgICBLYNARIOAwERNAMiNANEUAMIgQpBj7UBcZblFI4aDBAQJEBWAQtBZYJbEAQUH/wqLkf/4AhCAA4KCxEANQJMMg///hCDH4RQCmACB+DLBAoMEEYMQAQNAjAOBFgxyCQZrDBeIPAGowjCRJUBFIQtBgygSAQUD/5GNCAXAGAS3CIhotRh4CBoOADIOAFQOAhAGBiAdBkAJBoBiBwA3BwA0BwIcBYoQAHv5+BnKbBCwItRoBiB4AZBvzDHYQMMHwMgIIUQEYMgEYNAFpEQFQMQFQL0BVJcf/wtBUYigHS4w0BiICBoQwBwhEBghEBhBEBiBEBmQXBngfGFokPSIJbIdgb8HKQIDBdg4WCIgIgBMQwQBGYIlGbwMAuACBjACBPwUGGAkOAQNgA4YTCZoI6Fg7OCGoIWCgE4AQMwDgYHBCAQyCFgQNCgIoBDgYCBFAQeCDII7CLYZyBoATBsIIBkgWDgGgJoIFBjCDBsCGCZwIMBGoJaB8AiBmAOBjA/BJAQcBKYp9EVoQACkAhBoBqBwGQgMCfgMYfgNAwEJG4McSYIWCABA9Bv//+IGBiTaEABATB/gNKJgWQLgMfCYR6CC5o0CoACEYQQCCQAJgBQYYAEA=='))),
      32,
      atob("BgYIEA4SDwQHBwgNBAkEBw8IDQ0PDQ4NDg4EBA0NDQ0YEBEQEw8OEhMHCxANFhMTEBMQDg0SDxkODg8HBwcNDA4NDw0PDgcQDwYGDQYZDw4PDwkLCQ8MEwsMCwcHBw0A"),
      23+(this.scale<<8)+(1<<16)
    );
  }
  setFontB() {
    this.tela.setFontCustom(E.toString(require('heatshrink').decompress(atob('AFkYBZUBzgMK9/IBZMH+XABhNEvgYK/+ABhMf6CI7tf/8iHI3/6q2kMJGQt//oALFhf9gEFoEUNg34gkAtwjGl/0t8B/wLGt/l39GBY+/83/pYLGgP/zf/rY+BAAlb/2v/1v/AXGq3//t/PA8L/48ByCQIjf+OwyfG/waIgX/AAP5T5MVgxYGgQHBg2/8u0LAoTCqtW/HQBgm9C4P/9MC8SsFhML/JYBg8gHgnHpf0AwUSDAny4YLDgAYElt0/gGDgYEE58+D4mwAgc48/AAgMFoEdDAnOv+VrX/6GHCIQABnn1SYP+oP2+CHE6/5qtVt/2cQsPr6tC8yhGv1bEgL+BXQ3/0tW37GHgIkC8jrIrWlfJYAKXAIAJvOkBZMPv2gBZED7+8AgMEBg199dAfQP/wAkFvnwjf+ytvIYkB+ddt7uBjepDAkskf/yFpBgPQHolA39C/0BAYIYEhMfVgML/50Fl+L//5t/+QA1r/+R37eFBouQBZEBsqzPCBdOMYgAF3XcA4sFAYV/nvAUQuVAYMumfdBYkn75sBj9LngxEhv3D4MLwe27xhE93wgEH6GXzuwBgcrFYMB+EC/nXXQl+EgO4gH34twBgc39kAnoBBlsDDAl98EfokfoPQDAk75/v4WH6ENlQLDgXvn+S8X0gGTMYkd/sG/H9AwJBBAAf3//9v4FBjwLEgfm/N/LIMBfQsP/W/YZMf/7PKAAkGBhfYBZUJFJftwAGE0IEDhwlEgU9D4NFoEC7JnBAAWvvEA07dBvksfInrgP3vR1BoYYDfIPx+m7+EH8E4DAce9f4ge77f4paWDgPfklQ2/v/t1+BQE/38n9/ql+nxiE+39j+d///p5WEg/lt/g+3/w7vBXQvggf1rf8R4sayEAhf//KfJgtUaxwAHigKJgO//tYBZH+o1vQ4YAE30C2+0BY9+K4O7DA8fpUL94YHhfbw/+++qOoKWE8/i/Hvn//f4IACgX6+v9h3z4Fqagn+/o+B/c8hSvDgP6/9/oG/mfAsgYDg3/z+B3/yn39HokVr+S/1vgf+KwsGoEa3/wfAoADv//o6VIgEW9ngXZOn1DUK1ILKgILKqAEDUYkB1/5Awc8XQn/9VgAwUPwAECgdtoGcA4UD+AYDrf/gekAwXtBYcD3+AuZ6CnZCDgO71f7mj+CsYYDt+//fzGIML4iLDh336F/vj+B+EcDAf7vkD/P0g/4g5WDh966E/5f//EAKwn3z0C/8b/Egvp7E1Hgh/+oO9j7VEvOOgG+//+hfQBYcHwPggX1qsf+i3EnEtB4P+/4LFgdj4CxC8jQFjuwbhMHtDpKAAcC34lGcYg+GAAUffQMbMYiYD8lv/1fPggjC8J8B/y+BMov1/+W1G6EosB/P/rf/+3eDAt939f8tH5rHEgEvv9f6OAj2rHgvfxfQ9cA8SPEgXr6/QnXAh0bDAm68XQhdwgPgDAke+lQgHugE9h5hE3gDBhvUl9B8AMD9QDC7u/6E8BYcYRwUPuhQBwB6DCAd5/ECN4paD+kB/jxJV4LtJg2pfxwADhJEDAA0D3AsK24YCgI+G984CAX/0usBYcO+fAMYP+gX/U4IAC/8sBYP9EwNZBYcP2vQBYMYg30GIn3r0B/0vo4LFVQPg30vw/4K4u0h2+t/XBY0HoP+t/n/JwGms+3/2JQLDGu//8wXHgEd8tGF4yEC0EC0i/Ni2QBZMv//QBZEf///bJELQ4MuBIsZoEDSYWwFo1A3kYeYIlEh9apUvj0GyDNBAAUD7/rr/Xw//oLmBAAV36EE+vi/24hgkE2gzBnm+gXADAnvyEH59foE4DAkN9kA+336EHoAYE73Av18MYPwJQkO/e/z9ugF8gdABgf7v/X8/p38IuCREvtH/P+tVHzqIEnv//1/l2b64kEgXn/0v4Fv8S6Fhflt/gAoIXEVwa5CAA8a0gLJAA0QAokb/+QAoUGBYkf/WvI4ZCCJQXm/+fIgZjE+/+194AwMH0AMDvv4skNW4TBBcAd9CwNcgEKnY1DgPrTgMB4ELx2wDAct+YSBhEH6YbBHofPmgYBo/wdoIMDngYClf0gJiEDAM9OQP4gG4PYkt3P//4LBlyaF+fW//kDQLHFhef6CZCOIQADn1vVwMfHggAC/sETwILHgX/1X/BY5tBJQLUDAHkYJhACCzgLGgs4AYPv5ALFh3zSYMH+SXGt7JBgFEvgLFh/nDAX/cwIAE2jTBXgLACgA='))),
      46,
      atob("DQ4UDxMSExMUEBUUCg=="),
      50+(scale<<8)+(2<<16)
    );
  }
}
exports = screenChronvs
